name: K1 High FPS Fixes 1.1.1 Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    if: github.event.head_commit.message == 'Update K1 and K2 High FPS fixes'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create K1 release
        env:
          GH_TOKEN: ${{ github.token }}
        run: >-
          gh release create 1.1.1
          K1HighFPSFixes/K1HighFPSFixes.kpatch
          --title "1.1.1"
          --notes "Updated for Kotor Patch Manager 0.7.0 and minor bug fixes."
